# Generated by Django 4.0 on 2021-12-24 01:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='prueba',
            options={'ordering': ['titulo'], 'verbose_name': 'Inicio', 'verbose_name_plural': 'Pagina de incio'},
        ),
        migrations.AlterUniqueTogether(
            name='prueba',
            unique_together={('titulo', 'subtitulo')},
        ),
    ]
