# Generated by Django 4.0 on 2021-12-24 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departamento', '0002_habilidades_alter_departamento_options_and_more'),
        ('persona', '0002_alter_empleado_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='empleado',
            name='habilidad',
            field=models.ManyToManyField(to='departamento.Habilidades'),
        ),
    ]
